#!/bin/sh

# Run unburden-home-dir's test suite under Debian's autopkgtest
# Author: Axel Beckert <abe@debian.org>

set -e

# Compatibility with autopkgtest < v4
if [ -z "$AUTOPKGTEST_TMP" -a -n "$ADTTMP" ]; then
    AUTOPKGTEST_TMP="$ADTTMP"
    export AUTOPKGTEST_TMP
fi

# Copy test tree to $AUTOPKGTEST_TMP
cp -pvr t "$AUTOPKGTEST_TMP/t"
cd "$AUTOPKGTEST_TMP"

prove -v -j1
